name: example
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  devtool:
    path: ..
  cupertino_icons: ^0.1.3
  freezed_annotation: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.11.0
dependency_overrides:
  flutter_riverpod:
    path: ../../../packages/flutter_riverpod
  riverpod:
    path: ../../../packages/riverpod

flutter:
  uses-material-design: true
